BeStyle.FrontEnd.WebUI/Controllers/ConstructorController.cs
using BeStyle.Repositories.Abstract;
using BeStyle.WebUI.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeStyle.FrontEnd.WebUI.Models;
using BeStyle.Entities;
using System.Text;

namespace BeStyle.FrontEnd.WebUI.Controllers
{
    public class ConstructorController : Controller
    {
        #region Private Fields

        private readonly IProductRepository _productRepository;
        private readonly ISizeRepository _sizeRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISecurityManager _securityManager;
        private readonly ILogoRepository _logoRepository;

        #endregion

        #region Constructors

        public ConstructorController(
            IProductRepository productRepository,
            ISizeRepository sizeRepository,
            ICategoryRepository categoryRepository,
            ISecurityManager securityManager,
            ILogoRepository logoRepository)
        {
            this._productRepository = productRepository;
            this._categoryRepository = categoryRepository;
            this._sizeRepository = sizeRepository;
            this._securityManager = securityManager;
            this._logoRepository = logoRepository;
        }

        #endregion

        #region Web Actions

        public ActionResult Index()
        {
            ConstructorModel constructor = new ConstructorModel();
            constructor.Products = _productRepository.GetProductsAll();
            constructor.Sizes = _sizeRepository.GetSizes();
            constructor.Categories = _categoryRepository.GetAllCategory();
            constructor.Logos = _logoRepository.GetAllLogos();
            constructor.CurrentProduct = GetCurrentProduct();
            if (_securityManager.IsAuthenticated)
            {
                constructor.UserLogos = _logoRepository.GetLogosForCurrentUser(_securityManager.User.UserId);
            }

            return View(constructor);
        }

        #endregion

        #region Helpers

        private ProductEntity GetCurrentProduct()
        {
            ProductEntity product = (ProductEntity)Session["Product"];
            if (product == null)
            {
                product = new ProductEntity();
                product = _productRepository.GetProductById(2);
                Session["Product"] = product;
            }
            return product;
        }

        #endregion
    }
}

BeStyle.FrontEnd.WebUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BeStyle.Entities;
using BeStyle.FrontEnd.WebUI.Models;
using BeStyle.Repositories.Abstract;
using BeStyle.WebUI.Security;


namespace BeStyle.FrontEnd.WebUI.Controllers
{
    public class ShopController : Controller
    {
        #region Private Fields

        private readonly IProductRepository _productRepository;
        private readonly ISizeRepository _sizeRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISecurityManager _securityManager;
        private readonly ICommentRepository _commentRepository;

        #endregion

        #region Constructors

        public ShopController(IProductRepository productRepository, ISizeRepository sizeRepository, ICategoryRepository categoryRepository, ISecurityManager securityManager, ICommentRepository commentRepository)
        {
            this._productRepository = productRepository;
            this._categoryRepository = categoryRepository;
            this._sizeRepository = sizeRepository;
            this._securityManager = securityManager;
            this._commentRepository = commentRepository;
        }

        #endregion

        #region WebActions

        [HttpGet]
        public ActionResult Shop()
        {
            ShopModel products = new ShopModel
            {
                Products = _productRepository.GetProductsAll(),
                TopProducts = _productRepository.GetTopProducts(10), 
                Sizes = _sizeRepository.GetSizes(), 
                Categories = _categoryRepository.GetAllCategory(),
                Comments=_commentRepository.GetComments()                
            };
            products.MinPrice = 0;
            products.MaxPrice = products.Products.Count != 0 ? products.Products.Max(p => p.Price) : 0;

            return View(products);
        }

        [HttpGet]
        public ActionResult ShopByCategory(int? categoryId)
        {
            ShopModel products = new ShopModel();
            products.Products = categoryId.HasValue
                    ? _productRepository.GetProductsByCategoryId(categoryId.Value)
                    : _productRepository.GetProductsAll();
            products.TopProducts = _productRepository.GetTopProducts(10);
            products.Sizes = _sizeRepository.GetSizes();
            products.Categories = _categoryRepository.GetAllCategory();
            products.Comments = _commentRepository.GetComments();            
            products.MinPrice = 0;
            products.MaxPrice = products.Products.Count != 0 ? products.Products.Max(p => p.Price) : 0;
            
            return View("Shop", products);
        }

        [HttpGet]
        public ActionResult ShopByPrice(int start, int end, int? categoryId)
        {
            IList<ProductEntity> products = categoryId.HasValue
                ? _productRepository.GetProductsByPriceAndCategories(start, end, categoryId.Value)
                : _productRepository.GetProductsByPrice(start, end);

            return PartialView("_ProductListPartial", products);
        }

        [HttpPost]
        public ActionResult AddComment(int productId, string comment)
        {
            int userId=_securityManager.User.UserId;
            _commentRepository.SetComment(userId, productId, comment);
            DateTime dt=DateTime.Now;
            string user=_securityManager.User.UserName;
            var result = new { User = user, Comment = comment, Time = dt.ToLongTimeString() };
            return Json(result);
        }

        [ChildActionOnly]
        public ActionResult HeaderBottom()
        {
            var category = _categoryRepository.GetAllCategory();
            return PartialView("_HeaderBottom", category);
        }
        
        [HttpGet]
        public ActionResult ProductPartial(int id)
        {
            var model = new ProductModel()
            {
                Product = _productRepository.GetProductById(id),
                Comments = _commentRepository.GetCommentsForProduct(id),
                Sizes = _sizeRepository.GetSizes(),
                IsAuthenticated = _securityManager.IsAuthenticated
            };

            Session["Product"] = _productRepository.GetProductById(id);

            return PartialView("_ProductPartial", model);
        }

        #endregion
    }
}

BeStyle.FrontEnd.WebUI/Views/Shop/Shop.cshtml
@model BeStyle.FrontEnd.WebUI.Models.ShopModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "BeStyle online shop";
}
@section Scripts{
    @Scripts.Render("~/bundles/Shop/scripts")
}

<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="1"></li>
                        <li data-target="#slider-carousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="col-sm-6">
                                <h1><span>BE</span>-STYLE</h1>
                                <h2>BeStyle</h2>
                                <p>We carry a wide assortment of clothing in your size. Find capris, tops, sweaters, & more. Shop now to find the perfect addition to your outfit. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/App_Themes/Default/Images/home/girl1.jpg" class="girl img-responsive" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>BE</span>-STYLE</h1>
                                <h2>100% Responsive Design</h2>
                                <p>Experience global fashion in just a click through our mix of international labels, local brands and designers. Journey through to find your style.</p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/App_Themes/Default/Images/home/girl4.png" class="girl img-responsive" alt="" />
                            </div>
                        </div>

                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>BE</span>-STYLE</h1>
                                <h2>BeStyle</h2>
                                <p>Shop for the latest clothes online</p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="~/App_Themes/Default/Images/home/girl5.png" class="girl img-responsive" alt="" />
                            </div>
                        </div>

                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <div class="panel-group category-products" id="accordian">
                        <!--category-productsr-->
                        @foreach (var category in Model.Categories)
                        {
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">@Html.ActionLink(@category.Category, "ShopByCategory", "Shop", new { categoryId = @category.Id }, null)</h4>
                                </div>
                            </div>
                        }
                    </div><!--/category-products-->
                    <div class="price-range">
                        <!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well text-center">
                            <div id="slider-range"></div>
                            <input type="text" id="amount-start" data-price="@Model.MinPrice" class="pull-left" readonly style="margin: 5px; border: 0;  font-weight: bold; width: auto; width: 50px">
                            <input type="text" id="amount-end" data-price="@Model.MaxPrice" class="pull-right" readonly style="border: 0; margin: 5px; text-align: right; font-weight: bold; width: auto; width: 50px">
                        </div>
                    </div><!--/price-range-->
                </div>
            </div>

            <div class="col-sm-9 padding-right">

                <div class="recommended_items">
                    <!--recommended_items-->
                    <h2 class="title text-center">top items</h2>

                    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="item active">
                                @{
                                    int i = 0, maxItems = Model.TopProducts.Count;
                                    const int maxInSlide = 3;

                                    foreach (var top in Model.TopProducts)
                                    {
                                        if (i < maxInSlide)
                                        {
                                            <div class="col-sm-4">
                                                <div class="product-image-wrapper">
                                                    <div class="single-products">
                                                        <div class="productinfo text-center">
                                                            <img src="data:image/png;base64,@Convert.ToBase64String(top.Picture)" alt="" />
                                                            <h2>$@top.Price</h2>
                                                            <p>@top.Name</p>
                                                            <a href="@Url.Action("ProductPartial", new { id = top.Id })" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                                                        </div>
                                                        <img src="~/App_Themes/Default/Images/Icons/top_1.jpg" class="new" style="width: 35px;" alt="">
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                        else
                                        {
                                            break;
                                        }
                                        i++;
                                    }
                                }
                            </div>
                            @for (; i < maxItems; )
                            {
                                <div class="item">
                                    @do
                                    {
                                        <div class="col-sm-4">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        <img src="data:image/png;base64,@Convert.ToBase64String(Model.TopProducts[i].Picture)" alt="" />
                                                        <h2>$@Model.TopProducts[i].Price</h2>
                                                        <p>@Model.TopProducts[i].Name</p>
                                                        <a href="@Url.Action("ProductPartial", new { id = Model.TopProducts[i].Id })" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                                                    </div>
                                                    <img src="~/App_Themes/Default/Images/Icons/top_1.jpg" class="new" style="width: 35px;" alt="">

                                                </div>
                                            </div>
                                        </div>
                                        i++;
                                    } while (i % maxInSlide != 0 && i < maxItems);
                                </div>
                            }
                        </div>
                        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div><!--/recommended_items-->

                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    <div id="products-container">

                        @foreach (var item in Model.Products)
                        {
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <img src="data:image/png;base64,@Convert.ToBase64String(item.Picture)" alt="" />
                                            <h2>$@item.Price</h2>
                                            <p>@item.Name</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <h2>$@item.Price</h2>
                                                <p>@item.Name</p>
                                                <a href="@Url.Action("ProductPartial", new { id = item.Id })" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div><!--features_items-->

            </div>
        </div>
    </div>
</section>

BeStyle.FrontEnd.WebUI/Views/Shop/_ProductListPartial.cshtml
@model IList<BeStyle.Entities.ProductEntity>

@foreach (var item in Model)
{
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="data:image/png;base64,@Convert.ToBase64String(item.Picture)" alt="" />
                    <h2>$@item.Price</h2>
                    <p>@item.Name</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$@item.Price</h2>
                        <p>@item.Name</p>
                        <a href="@Url.Action("ProductPartial", new {id = item.Id})" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Details</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

BeStyle.FrontEnd.WebUI/Views/Shop/_ProductPartial.cshtml
@model BeStyle.FrontEnd.WebUI.Models.ProductModel

@{
    ViewBag.isCommentsHidden = true;
}

<div class="modal-content">

    <div class="modal-header">
        <button class="close" type="button" id="btn-close" data-dissmiss="modal">&times;</button>
        <div class="thumbnail product-image-border">
            <img src="data:image/png;base64,@Convert.ToBase64String(Model.Product.Picture)" style="height: 400px;">
        </div>
    </div>
    <div class="modal-body">
        <div class="caption">
            <h4 class="pull-right">$@Model.Product.Price</h4>
            <h4 class="pull-left">@Model.Product.Name</h4>
        </div>
        <br />
        <br />
        <br />
        <div class="btn-group" data-toggle="buttons">
            @foreach (var size in Model.Sizes)
            {
                <label class="btn btn-default btn-size" data-size-id="@size.Id">
                    <input type="radio" value="@size.Size" /> @size.Size
                </label>
            }
        </div>
        <div class="panel-group pull-right orange-tooltip" title="Open product in constructor" data-toggle="tooltip" data-placement="bottom">
            <a href="@Url.Action("Index", "Constructor")">
                <img src="~/App_Themes/Default/Images/Icons/vector-icon.png" class="constructor-link hvr-pulse-shrink" alt=""/>
            </a>
        </div>
        <br />
        <br />
        <p>
            <h4>Description: @Model.Product.Description</h4>
        </p>
        <br />
        <div class="adding">
        </div>
    </div>
    <div class="modal-footer">
        <div id="growl"></div>
        <div id="data-for-add" data-size-id="1"></div>
        <button type="button" class="AddLink Submit btn btn-primary center-block" width="150" data-product-id="@Model.Product.Id">Add to cart</button>
    </div>

    @* ***************COMMENTS***************** *@

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a id="comments-state" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Show Comments...</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="category-tab shop-details-tab">
                        @*category-tab*@

                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">

                                    @{
                                        var hide = Model.IsAuthenticated ? "" : "hide";
                                        <div class="@hide">
                                            <p>
                                                <b>Write Your Review</b>
                                            </p>

                                            <form action="#">
                                                <textarea id="commentText" name="" height="60"></textarea>
                                                <button type="button" class="AddComment Submit btn btn-primary center-block" data-product-id="@Model.Product.Id" width="150">Submit</button>
                                                <br>
                                            </form>
                                        </div>
                                    }

                                    <div class="col-sm-12">
                                        <ul class="nav nav-tabs" style="background: #40403E;">
                                            <li class="active"><a href="#reviews" data-toggle="tab">Reviews (@Model.Comments.Count)</a></li>
                                        </ul>
                                    </div>

                                    <div id="all-comment">
                                        <div id="new-comment"></div>
                                        @foreach (var comment in Model.Comments)
                                        {
                                            <ul>
                                                <li><a href=""><i class="fa fa-user">@comment.UserName</i></a></li>
                                                <li><a href=""><i class="fa fa-clock-o">@comment.CommentTime</i></a></li>
                                                <p>@comment.Comment</p>
                                            </ul>
                                        }
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!--/category-tab-->

                </div>
            </div>
        </div>
    </div>



</div>